/* Cẩm nang thuật ngữ WPS — Vietnamese explanations for technical terms */
window.WPS_GLOSSARY = [
  // ===== Quy trình hàn =====
  {term:"FCAW", vi:"Hàn dây lõi thuốc (Flux-Cored Arc Welding)", note:"Dây hàn có lõi thuốc bên trong. Khí bảo vệ thường là CO₂ hoặc Ar+CO₂. Năng suất cao, dùng nhiều ngoài công trường."},
  {term:"GMAW", vi:"Hàn dây đặc MIG/MAG (Gas Metal Arc Welding)", note:"Dây đặc, dùng khí bảo vệ (MIG = khí trơ Ar, MAG = khí hoạt tính CO₂). Đẹp, ít xỉ."},
  {term:"GTAW", vi:"Hàn TIG (Gas Tungsten Arc Welding)", note:"Điện cực vonfram, khí Argon. Mối hàn rất sạch, đẹp, thường dùng cho inox và lớp đầu (root pass)."},
  {term:"TIG", vi:"Tên gọi khác của GTAW", note:"Tungsten Inert Gas. Giống GTAW."},
  {term:"MIG", vi:"Hàn khí trơ", note:"Metal Inert Gas. Một dạng GMAW dùng khí Ar."},
  {term:"MAG", vi:"Hàn khí hoạt tính", note:"Metal Active Gas. GMAW dùng khí CO₂ hoặc Ar+CO₂."},
  {term:"SAW", vi:"Hàn hồ quang chìm (Submerged Arc Welding)", note:"Dây hàn chui qua lớp thuốc bột phủ trên kim loại. Tự động, năng suất rất cao, dùng cho mối hàn ngang dài."},
  {term:"SMAW", vi:"Hàn que (Shielded Metal Arc Welding)", note:"Hàn tay bằng que hàn có vỏ thuốc. Truyền thống, đơn giản."},

  // ===== Tư thế hàn =====
  {term:"1G", vi:"Tư thế phẳng (Flat)", note:"Tấm thép nằm ngang, hàn từ trên xuống. Dễ nhất."},
  {term:"2G", vi:"Tư thế ngang (Horizontal)", note:"Cấu kiện đứng, mối hàn nằm ngang."},
  {term:"3G", vi:"Tư thế đứng (Vertical)", note:"Mối hàn theo phương thẳng đứng. Có thể hàn từ dưới lên (uphill) hoặc trên xuống (downhill)."},
  {term:"4G", vi:"Tư thế trần (Overhead)", note:"Hàn ngược, nhìn lên. Khó nhất với tấm."},
  {term:"5G", vi:"Ống ngang cố định", note:"Ống nằm ngang không xoay. Phải hàn vòng quanh."},
  {term:"6G", vi:"Ống nghiêng 45° cố định", note:"Ống nghiêng 45° không xoay — kết hợp đủ mọi tư thế. Khó nhất, qualify được thì hàn được mọi tư thế ống."},
  {term:"6GR", vi:"Ống nghiêng 45° + vòng chặn (Restricted)", note:"Như 6G nhưng có vòng chặn (test ring) — qualify cho mối ống xuyên nút (T, K, Y)."},
  {term:"1F", vi:"Mối góc phẳng", note:"Mối hàn góc (fillet), cấu kiện đặt phẳng."},
  {term:"2F", vi:"Mối góc ngang", note:"Mối hàn góc, mối hàn nằm ngang."},
  {term:"3F", vi:"Mối góc đứng", note:"Mối hàn góc theo phương đứng."},
  {term:"4F", vi:"Mối góc trần", note:"Mối hàn góc, nhìn lên."},
  {term:"PA", vi:"Phẳng (ISO – tương đương 1G)", note:"ISO 6947. PA = Plat (Pháp)."},
  {term:"PB", vi:"Mối góc ngang (ISO – tương đương 2F)", note:""},
  {term:"PC", vi:"Ngang (ISO – tương đương 2G)", note:""},
  {term:"PD", vi:"Mối góc trần (ISO – tương đương 4F)", note:""},
  {term:"PE", vi:"Trần (ISO – tương đương 4G)", note:""},
  {term:"PF", vi:"Đứng – hàn LÊN (ISO uphill)", note:"Vertical-up. Pháp: 'Position Funéraire' (đi lên)."},
  {term:"PG", vi:"Đứng – hàn XUỐNG (ISO downhill)", note:"Vertical-down."},
  {term:"H-L045", vi:"Ống nghiêng 45° hàn LÊN", note:"ISO 6947. Tương đương 6G uphill."},
  {term:"J-L045", vi:"Ống nghiêng 45° hàn XUỐNG", note:"Tương đương 6G downhill."},
  {term:"Uphill", vi:"Hàn LÊN (đi từ dưới lên)", note:"Hồ quang đi từ dưới lên trên. Ngấu sâu, dùng cho mối hàn chịu lực."},
  {term:"Downhill", vi:"Hàn XUỐNG (đi từ trên xuống)", note:"Đi từ trên xuống. Nhanh, mịn, nhưng ngấu nông hơn."},
  {term:"Vertical Progression", vi:"Hướng tiến mối hàn đứng", note:"Up = lên, Down = xuống."},

  // ===== Mối hàn / Joint =====
  {term:"CJP", vi:"Ngấu toàn phần (Complete Joint Penetration)", note:"Mối hàn ngấu xuyên suốt toàn bộ chiều dày — chịu lực tối đa."},
  {term:"PJP", vi:"Ngấu một phần (Partial Joint Penetration)", note:"Chỉ ngấu một phần chiều dày — không chịu được toàn lực kéo."},
  {term:"BW", vi:"Mối hàn giáp mép (Butt Weld)", note:"Hai cấu kiện đối đầu nhau."},
  {term:"FW", vi:"Mối hàn góc (Fillet Weld)", note:"Mối hàn dạng tam giác ở góc giữa hai cấu kiện."},
  {term:"BU", vi:"Mối hàn build-up / đắp đầy", note:"Hàn đắp tăng dày bề mặt."},
  {term:"Groove", vi:"Mối hàn rãnh (vát)", note:"Có vát mép trước khi hàn. Có loại Square, V, U, J."},
  {term:"Fillet", vi:"Mối hàn góc", note:"Mối hàn tam giác giữa 2 tấm vuông góc."},
  {term:"T-joint", vi:"Liên kết chữ T", note:"Một tấm vuông góc với tấm kia."},
  {term:"Lap joint", vi:"Liên kết chồng", note:"Hai tấm chồng lên nhau, hàn ở mép."},
  {term:"Root opening / Root gap", vi:"Khe hở chân", note:"Khoảng cách giữa 2 cấu kiện ở đáy mối hàn. Thường 0-4 mm."},
  {term:"Root face", vi:"Mặt chân (gốc)", note:"Phần mép không vát ở chân mối hàn."},
  {term:"Groove angle", vi:"Góc vát mép", note:"Góc V hoặc U mở ra. Thường 30°, 45°, 60°."},
  {term:"Backing", vi:"Đệm lót", note:"Tấm/dải kim loại hoặc gốm đặt sau gốc để giữ kim loại nóng chảy."},

  // ===== Vật liệu cơ bản =====
  {term:"P-No", vi:"Số nhóm vật liệu (ASME)", note:"P-Number — gom các thép tương đương về tính hàn. P-No 1 = thép cacbon thường (A36, A572, SA516…). Qualify 1 thép trong nhóm là qualify được cả nhóm."},
  {term:"P-No 1", vi:"Thép cacbon thường", note:"Carbon steel ≤ 0.30%C. Bao gồm: A36, A53, A106, A572 Gr.50, SA516 Gr.70, S355, S275, SS400, A992, Q235, Q345, Q355…"},
  {term:"P-No 1 Group 1", vi:"Cacbon thấp (SMYS ≤ 290 MPa)", note:"A36, A53 Gr.B, A106 Gr.B, A500 Gr.B, SS400…"},
  {term:"P-No 1 Group 2", vi:"Cacbon trung bình (SMYS 290-415 MPa)", note:"A572 Gr.50, SA516 Gr.70, S355, Q345/Q355…"},
  {term:"P-No 8", vi:"Thép inox austenit", note:"Stainless 304/316/321/347 (austenitic). Dùng filler 308L, 316L, 309L (dissimilar)."},
  {term:"M-No", vi:"Phân loại vật liệu (AWS)", note:"M-Number, tương đương P-No của ASME. M-1 = cacbon, M-8 = inox austenit."},
  {term:"S-No", vi:"Phụ nhóm vật liệu cho ống (ASME B31)", note:"Code đường ống."},

  // ===== Filler =====
  {term:"F-No", vi:"Nhóm filler", note:"F-Number — gom các điện cực/dây hàn có đặc tính hàn tương đương. F-No 6 = phổ biến nhất (E70, E71T, ER70S-6)."},
  {term:"F-No 1", vi:"Rutile, vỏ acid", note:"E6010, E6011…"},
  {term:"F-No 2", vi:"Cellulose", note:"E6013, dễ hàn."},
  {term:"F-No 4", vi:"Vỏ basic / low-hydrogen", note:"E7018, dùng cho mối hàn chịu lực, vùng tới hạn."},
  {term:"F-No 6", vi:"Dây đặc / dây lõi thuốc thép thường", note:"ER70S-6 (GMAW), E71T-1C (FCAW), E70T-1…"},
  {term:"F-No 7", vi:"Que/dây inox austenit", note:"E308L, E309L, E316L…"},
  {term:"A-No", vi:"Phân loại thành phần hoá học kim loại đắp", note:"A-Number. A-1 = thép cacbon thường, A-8 = inox austenit."},
  {term:"SFA", vi:"Số tiêu chuẩn AWS A5.x", note:"AWS Specification — vd SFA-5.20 = FCAW thép cacbon."},
  {term:"AWS A5.18", vi:"Dây đặc GMAW thép cacbon", note:"ER70S-2, ER70S-3, ER70S-6…"},
  {term:"AWS A5.20", vi:"Dây lõi thuốc FCAW thép cacbon", note:"E71T-1, E71T-9, E70T-1…"},
  {term:"AWS A5.22", vi:"Dây lõi thuốc inox", note:"E308LT, E309LT, E316LT…"},
  {term:"AWS A5.17", vi:"Dây SAW + thuốc thép cacbon", note:"EM12K, EH14, EL12…"},
  {term:"AWS A5.9", vi:"Dây đặc GTAW/GMAW inox", note:"ER308L, ER309L, ER316L…"},
  {term:"ER70S-6", vi:"Dây đặc thép cacbon (GMAW)", note:"Phổ biến nhất cho hàn MIG/MAG. Si và Mn cao, dễ hàn."},
  {term:"E71T-1C", vi:"Dây lõi thuốc thép cacbon (FCAW)", note:"Hàn mọi tư thế, khí CO₂. Phổ biến nhất cho hàn kết cấu."},
  {term:"E308L", vi:"Inox 304L", note:"Cho thép A240 304/304L. L = low carbon, chống ăn mòn tốt."},
  {term:"E309L", vi:"Inox 309L — hàn DISSIMILAR (inox ↔ thép thường)", note:"Khi nối inox với thép cacbon — bắt buộc dùng filler 309L để chống nứt."},

  // ===== Khí bảo vệ =====
  {term:"Shielding Gas", vi:"Khí bảo vệ", note:"Khí thổi quanh hồ quang để chống oxy hoá. Ar, CO₂, He, hoặc hỗn hợp."},
  {term:"Argon (Ar)", vi:"Khí trơ — dùng cho GTAW, inox", note:"99.9% Ar cho TIG. Đắt nhưng cho mối hàn đẹp."},
  {term:"CO₂", vi:"Khí cacbonic — rẻ, dùng cho FCAW", note:"Ngấu sâu, hơi bắn nhiều, đẹp vừa."},
  {term:"Ar+CO₂ (75/25, 80/20)", vi:"Hỗn hợp Ar-CO₂", note:"Cân bằng giữa ngấu sâu và đẹp. Phổ biến cho GMAW."},
  {term:"Flow rate (LPM)", vi:"Lưu lượng khí (lít/phút)", note:"Thường 12-25 LPM tuỳ quy trình. Quá thấp → khí không bảo vệ đủ. Quá cao → tạo xoáy hút không khí vào."},

  // ===== Điện học =====
  {term:"DCEN", vi:"Dòng 1 chiều — cực âm trên electrode", note:"Direct Current Electrode Negative. Còn gọi 'straight polarity'. Ngấu sâu, ít nóng electrode. Dùng cho GTAW."},
  {term:"DCEP", vi:"Dòng 1 chiều — cực dương trên electrode", note:"Direct Current Electrode Positive. Còn gọi 'reverse polarity'. Ngấu cạn, đẹp. Dùng cho hầu hết SMAW/GMAW/FCAW."},
  {term:"DCSP", vi:"Tên cũ của DCEN", note:"Straight Polarity."},
  {term:"DCRP", vi:"Tên cũ của DCEP", note:"Reverse Polarity."},
  {term:"AC", vi:"Dòng xoay chiều", note:"Alternating Current. Dùng SMAW, ít dùng cho hàn kết cấu hiện đại."},
  {term:"CC", vi:"Nguồn dòng không đổi", note:"Constant Current. Dùng cho SMAW, GTAW. Volt thay đổi theo chiều dài hồ quang, Amp giữ nguyên."},
  {term:"CV", vi:"Nguồn áp không đổi", note:"Constant Voltage. Dùng cho GMAW, FCAW. Volt giữ nguyên, Amp thay đổi theo tốc độ dây."},
  {term:"WFS", vi:"Tốc độ dây cấp", note:"Wire Feed Speed. Quyết định ampe trong CV. Đo bằng m/phút hoặc inch/phút."},
  {term:"Travel Speed", vi:"Tốc độ di chuyển hồ quang", note:"mm/phút hoặc cm/phút. Chậm = ngấu sâu, đẹp; nhanh = ngấu nông."},
  {term:"Heat Input", vi:"Nhiệt lượng cấp vào", note:"= Volt × Amp × 60 ÷ Travel Speed (J/mm). Quá cao → vùng ảnh hưởng nhiệt (HAZ) rộng, cấu trúc tệ. Quá thấp → ngấu kém."},

  // ===== Xử lý nhiệt =====
  {term:"Preheat", vi:"Tiền nhiệt (nung trước khi hàn)", note:"Nung nóng vật liệu trước khi hàn để giảm tốc độ nguội. Tránh nứt nguội (hydrogen cracking)."},
  {term:"Interpass Temperature", vi:"Nhiệt độ giữa các lớp", note:"Nhiệt độ vật liệu trước khi hàn lớp tiếp theo. Có MIN và MAX. Quá cao → cấu trúc kém."},
  {term:"PWHT", vi:"Xử lý nhiệt sau khi hàn (Post Weld Heat Treatment)", note:"Nung sau khi hàn để giải toả ứng suất dư. Thường 600-650°C giữ 1 giờ. Bắt buộc với bồn áp lực."},
  {term:"Stress Relief", vi:"Giải toả ứng suất", note:"Tên gọi khác của PWHT."},

  // ===== Kỹ thuật =====
  {term:"Stringer", vi:"Hàn đường thẳng (không lượn)", note:"Hồ quang đi thẳng, không dao động. Ngấu sâu, lớp hẹp."},
  {term:"Weave", vi:"Hàn lượn sóng (zíc-zắc)", note:"Hồ quang lượn ngang. Lớp rộng hơn, ngấu nông hơn. Dùng khi cần đắp đầy nhiều."},
  {term:"Oscillation", vi:"Dao động ngang", note:"Hồ quang dao động ngang trong khi tiến. Tự động hoặc bằng tay."},
  {term:"Multi-pass", vi:"Hàn nhiều lớp", note:"Mối hàn dày phải hàn nhiều lớp chồng lên nhau."},
  {term:"Single-pass", vi:"Hàn 1 lớp duy nhất", note:""},
  {term:"Root pass", vi:"Lớp đầu (đáy mối hàn)", note:"Lớp ngấu xuyên qua chân mối hàn. Quan trọng nhất."},
  {term:"Fill pass", vi:"Lớp đắp giữa", note:"Lớp đắp đầy mối hàn."},
  {term:"Cap pass", vi:"Lớp phủ ngoài cùng", note:"Lớp cuối, định hình bề mặt mối hàn."},
  {term:"Interpass Cleaning", vi:"Làm sạch giữa các lớp", note:"Bàn chải sắt, đá mài. Loại xỉ, vảy, dầu mỡ trước khi hàn lớp kế tiếp."},
  {term:"Gouging", vi:"Cắt rãnh / mài gốc", note:"Cắt bỏ lớp gốc kém chất lượng trước khi hàn ngược lại. Bằng đá mài hoặc carbon arc."},
  {term:"Peening", vi:"Đập búa lên mối hàn", note:"Đập nhẹ búa lên lớp hàn nóng để giảm ứng suất."},
  {term:"Spatter", vi:"Bắn xỉ", note:"Hạt kim loại văng ra khi hàn. Càng ít càng tốt."},
  {term:"Slag", vi:"Xỉ hàn", note:"Lớp vảy thuốc đông cứng trên mối hàn. Phải gõ bỏ trước khi hàn lớp tiếp."},
  {term:"Transfer Mode", vi:"Kiểu truyền kim loại (GMAW)", note:"Spray (phun), Globular (cầu rơi), Short circuit (ngắn mạch), Pulse (xung)."},

  // ===== Kiểm tra =====
  {term:"CVN", vi:"Thử va đập Charpy V-Notch", note:"Đo độ dai vùng hàn. Thường yêu cầu min 27J hoặc 34J ở -20°C cho thép kết cấu ngoài trời."},
  {term:"Impact Test", vi:"Thử va đập (Charpy)", note:"Cùng nghĩa với CVN."},
  {term:"NDE / NDT", vi:"Kiểm tra không phá huỷ", note:"Non-Destructive Examination/Testing. VT (mắt thường), PT (chất thấm), MT (từ tính), UT (siêu âm), RT (chụp X-quang)."},
  {term:"VT", vi:"Kiểm tra bằng mắt", note:"Visual Test. 100% mối hàn phải qua."},
  {term:"UT", vi:"Kiểm tra siêu âm", note:"Ultrasonic Test. Phát hiện khuyết tật bên trong mối hàn."},
  {term:"RT", vi:"Kiểm tra chụp X-quang", note:"Radiographic Test. Cho ảnh khuyết tật bên trong."},
  {term:"PT", vi:"Kiểm tra chất thấm", note:"Penetrant Test. Phát hiện nứt nhỏ trên bề mặt."},
  {term:"MT", vi:"Kiểm tra từ tính", note:"Magnetic Particle Test. Phát hiện nứt bề mặt và gần bề mặt (chỉ thép từ)."},

  // ===== Tiêu chuẩn =====
  {term:"AWS D1.1", vi:"Tiêu chuẩn hàn kết cấu thép Mỹ", note:"American Welding Society D1.1 — Structural Welding Code Steel. Phổ biến nhất cho kết cấu thép."},
  {term:"AWS D1.6", vi:"Tiêu chuẩn hàn kết cấu inox", note:"D1.6 — Structural Welding Code Stainless Steel."},
  {term:"AWS D1.3", vi:"Hàn tôn mỏng (<5mm)", note:"Sheet steel."},
  {term:"ASME IX", vi:"Tiêu chuẩn hàn ASME Section IX", note:"ASME BPVC Section IX — Qualification Standard for Welding Procedures. Dùng cho bồn áp lực, đường ống."},
  {term:"ISO 15614", vi:"Tiêu chuẩn qualify quy trình hàn Châu Âu", note:"Test specimens for welding procedure qualification."},
  {term:"ISO 15609", vi:"Format WPS theo ISO", note:"Specification and qualification of welding procedures — written WPS format."},
  {term:"API 1104", vi:"Tiêu chuẩn hàn đường ống dầu khí", note:"Welding of Pipelines and Related Facilities."},

  // ===== Khác =====
  {term:"PQR", vi:"Hồ sơ chứng minh quy trình hàn (Procedure Qualification Record)", note:"Bản ghi kết quả test mẫu hàn thực tế. PQR chứng minh WPS hoạt động được — bắt buộc phải có để 'support' cho WPS."},
  {term:"WPQR", vi:"Tên gọi khác của PQR (ISO)", note:"Welding Procedure Qualification Record."},
  {term:"WPS", vi:"Quy trình hàn đã viết (Welding Procedure Specification)", note:"Tài liệu hướng dẫn công nhân hàn. Dựa trên PQR, có thể mở rộng phạm vi (range qualified) theo code."},
  {term:"Range Qualified", vi:"Phạm vi được phép hàn", note:"Dải vật liệu/chiều dày/tư thế/đường kính mà WPS này cho phép — rộng hơn dải đã test ở PQR."},
  {term:"Essential Variable", vi:"Biến thiết yếu", note:"Yếu tố mà nếu thay đổi vượt giới hạn, PHẢI test lại PQR. Vd: code, vật liệu cơ bản, filler F-No."},
  {term:"Non-essential Variable", vi:"Biến không thiết yếu", note:"Có thể thay đổi mà không cần qualify lại — chỉ cần sửa WPS."},
  {term:"Supplementary Essential", vi:"Biến thiết yếu bổ sung (khi có yêu cầu impact)", note:"Khi WPS yêu cầu thử Charpy, các biến này cũng trở thành thiết yếu."}
];
