/* Gallery v2 — Tìm ảnh thật trên Google/Bing trực tiếp.
   Mỗi mục có search query tiếng Anh chuẩn → mở Google Images/Bing Images
   với 1 click. User cũng có thể save ảnh vào folder local images/<id>.jpg
   để app dùng làm thumbnail ưu tiên. */
window.LD_GALLERY = [

  /* ===== WELDING DEFECTS ===== */
  { id:'undercut', cat:'weld', title:'Cháy chân (Undercut)',
    query:'weld undercut defect macro photo',
    desc:'Rãnh khuyết tại chân mối hàn — visible bằng mắt thường + undercut gauge' },
  { id:'porosity', cat:'weld', title:'Rỗ khí trên surface',
    query:'weld porosity surface defect',
    desc:'Chấm tròn rỗ khí phân tán trên bề mặt mối hàn' },
  { id:'porosity-rt', cat:'weld', title:'Rỗ khí qua phim RT',
    query:'weld radiograph porosity X-ray film',
    desc:'Chấm đen tròn trên phim X-quang RT' },
  { id:'crack-hot', cat:'weld', title:'Nứt nóng centerline',
    query:'weld hot crack centerline crack',
    desc:'Nứt dọc trục mối hàn ngay khi nguội' },
  { id:'crack-cold', cat:'weld', title:'Nứt nguội H₂ trong HAZ',
    query:'hydrogen induced cracking HAZ steel weld',
    desc:'Nứt 48-72h sau hàn — phải UT sau preheat fail' },
  { id:'crack-crater', cat:'weld', title:'Nứt sao crater (star crack)',
    query:'weld crater crack star',
    desc:'Nứt tỏa ra như sao ở vết lõm cuối đường hàn' },
  { id:'lof', cat:'weld', title:'Không ngấu Lack of Fusion — macro etch',
    query:'lack of fusion weld macro etch',
    desc:'Mặt cắt etch → đường tối giữa mối hàn và base metal' },
  { id:'lop', cat:'weld', title:'Không thấu Lack of Penetration root',
    query:'incomplete penetration root weld',
    desc:'Root joint không hàn ngấu hoàn toàn' },
  { id:'slag', cat:'weld', title:'Xỉ kẹt (Slag inclusion)',
    query:'slag inclusion weld radiograph',
    desc:'Vùng đen méo trên phim RT (khác rỗ khí tròn)' },
  { id:'spatter', cat:'weld', title:'Văng tia (Spatter)',
    query:'weld spatter steel',
    desc:'Hạt kim loại bắn ra ngoài đường hàn' },
  { id:'arc-strike', cat:'weld', title:'Hồ quang lạc (Arc strike)',
    query:'arc strike welding defect',
    desc:'Vết hồ quang ngoài đường hàn — vùng cứng' },
  { id:'distortion', cat:'weld', title:'Distortion sau hàn (méo dầm I)',
    query:'welding distortion I-beam',
    desc:'Méo cánh I do hàn không sequence' },
  { id:'fillet-good', cat:'weld', title:'Mối hàn fillet ĐẠT (tham chiếu)',
    query:'fillet weld good quality reference',
    desc:'Profile lồi nhẹ đều — leg + throat đúng' },
  { id:'butt-good', cat:'weld', title:'Mối hàn butt CJP đẹp',
    query:'butt weld CJP good quality macro',
    desc:'Full penetration với reinforcement đều' },
  { id:'mill-scale', cat:'weld', title:'Vảy cán mill scale',
    query:'mill scale steel surface hot rolled',
    desc:'Lớp FeO/Fe₃O₄ đen trên thép cán nóng' },

  /* ===== PAINT / COATING DEFECTS ===== */
  { id:'p-blister', cat:'paint', title:'Phồng sơn (Blistering)',
    query:'paint blistering coating defect',
    desc:'Bong bóng phồng chứa nước/khí dưới màng sơn' },
  { id:'p-peeling', cat:'paint', title:'Bong tróc (Peeling)',
    query:'paint peeling coating adhesion failure',
    desc:'Sơn bong khỏi bề mặt — không đạt pull-off test' },
  { id:'p-chalking', cat:'paint', title:'Phấn hoá (Chalking)',
    query:'paint chalking weathered UV',
    desc:'Bột trắng do UV bào mòn' },
  { id:'p-crack', cat:'paint', title:'Nứt sơn (Crazing/Cracking)',
    query:'paint cracking crazing coating',
    desc:'Mạng nứt do DFT quá dày hoặc UV' },
  { id:'p-runs', cat:'paint', title:'Chảy sơn (Runs/Sags)',
    query:'paint runs sags drips defect',
    desc:'Sơn chảy thành đường rủ — phun quá dày' },
  { id:'p-orange', cat:'paint', title:'Vỏ cam (Orange Peel)',
    query:'orange peel paint texture defect',
    desc:'Bề mặt nhô lồi như vỏ cam' },
  { id:'p-fish-eye', cat:'paint', title:'Mắt cá (Fish-eye)',
    query:'fisheye paint silicone contamination',
    desc:'Vùng tròn lõm có tâm do silicone' },
  { id:'p-pinhole', cat:'paint', title:'Lỗ kim (Pinhole) holiday',
    query:'pinhole coating holiday detector',
    desc:'Lỗ nhỏ xuyên màng sơn — phát hiện qua holiday test' },
  { id:'p-rust-bleed', cat:'paint', title:'Gỉ thấm qua (Rust bleeding)',
    query:'rust bleeding through paint coating',
    desc:'Vết gỉ nâu thấm xuyên màng sơn' },
  { id:'p-dft', cat:'paint', title:'Máy đo DFT (Elcometer/PIG)',
    query:'Elcometer 456 dry film thickness gauge',
    desc:'Đo dry film thickness theo ISO 19840' },
  { id:'p-sandblast', cat:'paint', title:'Sandblast Sa 2.5 ISO 8501',
    query:'Sa 2.5 sandblasted steel ISO 8501',
    desc:'Bề mặt chuẩn sau abrasive blast' },

  /* ===== DIMENSIONAL / TOOL ===== */
  { id:'d-caliper', cat:'dim', title:'Caliper điện tử',
    query:'digital caliper measurement steel',
    desc:'Đo lỗ + trục, chính xác 0.01-0.02mm' },
  { id:'d-micrometer', cat:'dim', title:'Panme (Micrometer)',
    query:'micrometer screw gauge measurement',
    desc:'Độ chính xác 0.001mm cho H6/h6' },
  { id:'d-theodolite', cat:'dim', title:'Laser theodolite',
    query:'total station theodolite construction',
    desc:'Đo plumb cột theo EN 1090-2' },
  { id:'d-pin-gauge', cat:'dim', title:'Pin gauge GO/NO-GO',
    query:'plug gauge GO NO-GO hole inspection',
    desc:'Kiểm dung sai lỗ ISO 286 H7/H8' },
  { id:'d-profile', cat:'dim', title:'Surface profile gauge Rz',
    query:'surface profile gauge Rz blast',
    desc:'Đo nhám sau sandblast (ISO 8503)' },
  { id:'d-i-distortion', cat:'dim', title:'I-beam distortion sau hàn',
    query:'welded I-beam distortion measurement',
    desc:'Cánh I cong vào do hàn không sequence' },
  { id:'d-flatness', cat:'dim', title:'Đo flatness tấm bằng straight edge',
    query:'plate flatness straight edge feeler',
    desc:'EN 10029 Class N đo trên đoạn 1m' },

  /* ===== NDE / INSPECTION ===== */
  { id:'n-ut', cat:'nde', title:'UT phased array',
    query:'phased array ultrasonic testing weld PAUT',
    desc:'Siêu âm phased array — ISO 19285' },
  { id:'n-rt', cat:'nde', title:'Phim RT (X-ray)',
    query:'radiographic testing weld film X-ray',
    desc:'Phim X-quang mối hàn' },
  { id:'n-pt', cat:'nde', title:'Penetrant Test (PT)',
    query:'dye penetrant inspection weld red',
    desc:'Thuốc nhuộm đỏ thấm vào nứt — ISO 3452' },
  { id:'n-mt', cat:'nde', title:'Magnetic Particle (MT)',
    query:'magnetic particle inspection weld MT',
    desc:'Bột từ phát hiện nứt nông trên ferromagnetic' },
  { id:'n-vt', cat:'nde', title:'Visual Test (VT) bằng đèn',
    query:'visual inspection weld lamp magnifier',
    desc:'Kiểm visual với đèn + kính lúp 5×-10×' },
  { id:'n-holiday', cat:'nde', title:'Holiday detector cho sơn',
    query:'holiday detector coating pinhole spark',
    desc:'67.5V/mil đo lỗ kim trong màng sơn' }
];

console.log('LD_GALLERY v2 loaded:', window.LD_GALLERY.length, 'defect categories with Google/Bing search');
